version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=MP77
      - POSTGRES_PASSWORD=IDecreeAndDeclareWarOnShitePerformance
      - POSTGRES_DB=prayer_db
    ports:
      - '5434:5432'